services:
  mongodb:
    image: mongo:7.0.5
    container_name: product-service-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Bundes9898
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db